[package]
name = "storm-collector"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
storm-core.workspace = true
storm-solana.workspace = true
storm-store.workspace = true
storm-pumpfun.workspace = true
storm-features.workspace = true

solana-client.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
