[package]
name = "storm-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
storm-core.workspace = true
storm-solana.workspace = true
storm-cex.workspace = true

solana-sdk.workspace = true
tokio.workspace = true
tokio-util.workspace = true
rust_decimal.workspace = true
tracing.workspace = true
